### GENERAL SETTINGS ###

# Site settings
title: "Mental Health Software for Psychologists, Social Workers, Therapists and Counselors."
analytics: #UA-40222088-2
baseurl: "/theranest-update" #important: start with /
url: "http://kaylacille.github.io/theranest-update"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#242B35" #"#33004D"
  green: "#9DC641"
  link: "#2ABDE3"
  link_hover: "#00b3fe"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/TheraNest
  - title: twitter
    url: https://twitter.com/theranest
  - title: pinterest-p
    url: https://www.pinterest.com/TheraNest/
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - 1500 1st Avenue North, Suite B124
    - Birmingham, Alabama 35203 
    - United States
email: info@theranest.com
tel: 1-800-867-7405


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Mental Health Software for Psychologists, Social Workers, Therapists and Counselors."

# Testimonial content. Shown on Home and About page. 
testimonial1:
    message: "All my therapists rave the ease of use, in documenting, scheduling and/or billing! Any questions or problems we think we have are addressed quickly. The training that they offer is easy to understand and comprehend. I recommend Theranest to all my therapist clients!"
    author: Davia Ward
    position: Practice Manager, Healthcare Partners Consulting and Billing

testimonial2:
    message: "Theranest does more, costs less, and is easier to use than any other all-in-one product I've tried. I have a small private practice and theranest simplifies all that yucky, paperwork, business end stuff so I can focus on what I love doing--meeting with my clients."
    author: Jeannette Rodriguez-March
    position: Owner/Art and Depth Psychotherapist, Goat Path Counseling

testimonial3:
    message: "Theranest has made the transition into running a private practice relatively seamless for me. I use it for all of my clinical scheduling, billing, and notes. This product is well-designed and their customer service is excellent! Highly recommend to all private-practice clinicians!"
    author: Caroline Adelman
    position: Founder, Chicago Psychotherapy, LLC